apiVersion: v1
kind: Pod
metadata:
  name: "resource-service"
  namespace: default
  labels:
    app: resource-service
spec:
  containers:
    - name: resource-service
      image: "pusti/rso2324-team22-resource-service:latest"
      ports:
      - containerPort: 80
        name:  http
      env:
        - name: POSTGRES_SERVER
          valueFrom:
            configMapKeyRef:
              name: postgres-config
              key: postgres_server
        - name: POSTGRES_DATABASE
          valueFrom:
            configMapKeyRef:
              name: postgres-config
              key: postgres_resources_database
        - name: POSTGRES_USERNAME
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: postgres_username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: postgres_password
      startupProbe:
        httpGet:
          path: /health/startup
          port: http
        initialDelaySeconds: 10
        periodSeconds: 10
---

apiVersion: v1
kind: Service
metadata:
  name: resource-service
spec:
  type: LoadBalancer
  selector:
    app: resource-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: http
